name: Build ModShot Ubuntu
on: workflow_dispatch
jobs:
  build-ubuntu:
    name: Build ModShot for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_ver: ['3.1', '3.0', '2.7']
        steam: [true, false]
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup Python
          uses: actions/setup-python@v2
        - name: Build
          working-directory: ${{ github.workspace }}
          run: |
              bash setup.sh
              pip3 install meson ninja
              cd linux
              make RUBY_VER=${{ matrix.ruby_ver }}
              source vars.sh
              cd ..
              meson build -Dmri_version=${{ matrix.ruby_ver }} --prefix=$PWD/out/ -Dsteam=${{ matrix.steam }}
              cd build && ninja install
        - name: Create dist folder
          run: |
            mkdir ${{ runner.temp }}/built_artifact;
            mv ${{ github.workspace }}/out/* ${{ runner.temp }}/built_artifact/;
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: modshot_build_ubuntu_rb-${{ matrix.ruby_ver }}_steam-${{ matrix.steam }}
            path: ${{ runner.temp }}/built_artifact
