name: Build Luminol-ModShot
on: 
  - workflow_dispatch
  - push

jobs:
  build-winnt:
    name: Build Luminol-ModShot on Windows
    runs-on: windows-2022
    strategy:
      matrix:
        include: 
          - { sys: ucrt64, env: ucrt-x86_64 }
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
      - name: Install/Build Dependencies for ModShot
        shell: msys2 {0}
        run: ./init.sh