name: Build ModShot Windows
on: workflow_dispatch
jobs:
  build-windows:
    name: Build ModShot for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_ver: ['3.0', '2.7']
        sys: ['mingw64']
        steam: [true, false]
        include: 
          - sys: 'ucrt64'
            ruby_ver: '3.1'
            steam: true
          - sys: 'ucrt64'
            ruby_ver: '3.1'
            steam: false
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Setup msys2
          uses: msys2/setup-msys2@v2
          with:
            msystem: ${{matrix.sys}}
        - name: Install packages with pacman
          shell: msys2 {0}
          run: |
            pacman -S --noconfirm  mm-common autoconf automake gcc make cmake libtool
        - name: Build
          working-directory: ${{ github.workspace }}
          shell: msys2 {0}
          run: |
              bash setup.sh
              cd windows
              make RUBY_VER=${{ matrix.ruby_ver }}
              source vars.sh
              cd ..
              meson build -Dmri_version=${{ matrix.ruby_ver }} --prefix=$PWD/out/ -Dsteam=${{ matrix.steam }}
              cd build && ninja install
        - name: Create dist folder
          run: |
            mkdir ${{ runner.temp }}\built_artifact;
            move ${{ github.workspace }}\out\* ${{ runner.temp }}\built_artifact\;
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: modshot_build_windows_rb-${{ matrix.ruby_ver }}-${{ matrix.sys }}_steam-${{ matrix.steam }}
            path: ${{ runner.temp }}\built_artifact